title: "Natacha NJONGWA YEPNGA"
logo: /img/nny.jpg
description: "Data Scientist | Analyste Quantitatif | Spécialiste IA et Modèles de Risque"
show_downloads: true
theme: jekyll-theme-minimal
author: "Natacha NJONGWA YEPNGA"
linkedin_username: natacha-njongwa-yepnga
github_username: natacha-njongwa-yepnga
youtube_url: "https://www.youtube.com/c/LeCoinStat"
email: "natacha.contact@email.com"

